### PR TITLE
Fix the notification pipe for squashfuse in case of failure

### LINKED ISSUE #112: notify_pipe option in squashfuse not sending failure
I should have tested -o notify_pipe before merging #110 into the master branch, but I did it afterward.  I tried both success and failures of mounts for both squashfuse_ll and squashfuse, and 3 of the combinations worked but squashfuse failures did not; there was no notification.  It would be good if the automated tests tried all four combinations.

Reproduce with
```
 $ mknod /tmp/notifypipe p
 $ cat </tmp/notifypipe
```
and in another window do
```
$ ./squashfuse -o notify_pipe=/tmp/notifypipe /dev/null /mnt
```
An `f` is only sent to the pipe if squashfuse_ll is used, but not if squashfuse is used.

@ariel-miculas

### PR DESCRIPTION
**Pull request by ariel-miculas**
The following scenario now correctly sends a failure notification to the pipe:
```
$ mkfifo /tmp/notify_pipe
$ cat /tmp/notify_pipe
```
then run squashfuse:
```
$ ./squashfuse -o notify_pipe=/tmp/notify_pipe /dev/null /mnt
```
This fix only applies to squashfuse, squashfuse_ll was behaving as expected.

Fixes #112

### CODE REVIEW

**Comment by DrDaveD** [comment]
Please include the expanded automated test you described in #112.  I would think that could be made more compact though, at least a loop with starting something like `for prog in squashfuse squashfuse_ll` and execute the same tests with both `$prog`.

While you're fixing things, also please break up that long new `-o notify_pipe=` line in `sqfs_usage` into two lines so no line is longer than 80 characters.

**Comment by ariel-miculas** [comment]
Added `tests/notify_test.sh` which checks both successful and unsuccessful squashfuse(_ll) mounts.

File: fuseprivate.c [hunk 1]
```diff
@@ -79,7 +79,8 @@ int sqfs_usage(char *progname, bool fuse_usage, bool ll_usage) {
 	fprintf(stderr, "\n%s options:\n", progname);
 	fprintf(stderr, "    -o offset=N            offset N bytes into ARCHIVE to mount\n");
 	fprintf(stderr, "    -o subdir=PATH         mount subdirectory PATH of ARCHIVE\n");
-	fprintf(stderr, "    -o notify_pipe=PATH    named pipe that will receive 's' (success) or 'f' (failure) when the mountpoint is ready\n");
+	fprintf(stderr, "    -o notify_pipe=PATH    named pipe that will receive 's' (success)"
+			" or 'f' (failure) when the mountpoint is ready\n");
```
Comment (DrDaveD) [inline fuseprivate.c:83]: Please indent the second line the way it is done on the `clone_fd` and `max_idle_threads` FUSE options, so the second line description starts at the same place as the first.

**Review by DrDaveD — CHANGES_REQUESTED** [review]
Yes, I can make a new release once this is merged.

File: fuseprivate.c (hunk 1 above)
Comment (ariel-miculas) [reply fuseprivate.c:83]: Ah, you're referring to the actual output of the function and not the C code formatting.

**Comment by DrDaveD** [comment]
Yes, that looks better.  Unfortunately the freebsd check failed, which it does sometimes, and the only way I have found to force that to re-run is to push a commit.  So please recreate the current commit and force push again.

**Comment by ariel-miculas** [comment]
The CI gods have shown mercy this time.

**Review by DrDaveD — APPROVED** [review]
